import { ReactNode } from "react";
import type { Metadata } from "next";
import { DM_Serif_Display, DM_Sans } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ThemeProvider } from "@/core/packages/theme";
import { AuthProvider } from "@/core/packages/auth";

import "@repo/ui/styles.css";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif-display",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZaaranżujTo",
  description: "Generated by create next app",
};

type TRootLayoutProps = {
  children: ReactNode;
};

export const RootLayout = async (props: TRootLayoutProps) => {
  const { children } = props;
  const messages = await getMessages();

  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={`${dmSans.variable} ${dmSerifDisplay.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};
